package Tempconvcalc;


/**
* Tempconvcalc/Tempcalc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tempconvcalc.idl
* Monday, 14 September, 2020 11:52:57 AM IST
*/

public interface Tempcalc extends TempcalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tempcalc
