package Tempconvcalc;

/**
* Tempconvcalc/TempcalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tempconvcalc.idl
* Monday, 14 September, 2020 11:52:57 AM IST
*/

public final class TempcalcHolder implements org.omg.CORBA.portable.Streamable
{
  public Tempconvcalc.Tempcalc value = null;

  public TempcalcHolder ()
  {
  }

  public TempcalcHolder (Tempconvcalc.Tempcalc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Tempconvcalc.TempcalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Tempconvcalc.TempcalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Tempconvcalc.TempcalcHelper.type ();
  }

}
