package Tempconvcalc;


/**
* Tempconvcalc/Tempcalc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tempconvcalc.idl
* Friday, 18 September, 2020 7:40:41 PM IST
*/

public interface Tempcalc extends TempcalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tempcalc
