package Tempconvcalc;


/**
* Tempconvcalc/TempcalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tempconvcalc.idl
* Friday, 18 September, 2020 7:40:41 PM IST
*/

public interface TempcalcOperations 
{
  double get_celsius (String symbol);
} // interface TempcalcOperations
