package Tempconvcalc;


/**
* Tempconvcalc/TempcalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Tempconvcalc.idl
* Monday, 14 September, 2020 11:52:57 AM IST
*/

public interface TempcalcOperations 
{
  double get_celsius (String symbol);
} // interface TempcalcOperations
